Feature/ssd core read
charmgreen/BestReviewer_SsdTestProject pull request #2
Opened 2024-07-08 07:19 UTC by yjyjy131

## 개요

## PR 유형
어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [x] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.  Commit message convention 참고  (Ctrl + 클릭하세요.) 
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-07-08 08:13 UTC, binaryfalse81 approved these changes

2024-07-08 08:13 UTC, binaryfalse81 commented on virtual_SSD/SSD.h
> +  virtual std::string Read(int lab) = 0;
read 기능 구현 확인

2024-07-08 08:14 UTC, m1nqm1nq approved these changes

2024-07-08 08:14 UTC, m1nqm1nq commented on virtualSSD-Test/test.cpp
> +  EXPECT_THROW({ ssd.Read(100); }, std::invalid_argument);
Read Testcase 확인했습니다~ 👍

2024-07-09 02:24 UTC, charmgreen requested changes
nand.txt, result.txt는 커밋에서 없어도 되는건가요?

2024-07-09 02:24 UTC, charmgreen commented on virtualSSD-Test/nand.txt
nand.txt는 초기에 존재하지 않는 상태여도 되는거면 커밋에서 빼야할 것 같습니다.

2024-07-09 02:24 UTC, charmgreen commented on virtualSSD-Test/result.txt
result.txt도 초기에 존재하지 않아도 되는 상태여도 괜찮은거면 커밋에서 뺴면 좋을 것 같습니다.

2024-07-09 02:32 UTC, charmgreen approved these changes
LGTM! 변경사항 확인했습니다.

2024-07-09 02:32 UTC, yjyjy131 commented on virtual_SSD/SSD.cpp
> +  bool isLabDataExistInMemory(int lab) {
오타 수정했습니다~!

2024-07-09 02:33 UTC, yjyjy131 commented on virtualSSD-Test/result.txt
넵 커밋에서 제외하고 gitignore 작성해두었습니다~

2024-07-09 02:33 UTC, merged